name: GitHub Actions Demo

on:
  push:
    branches:
      - my-first-branch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hola Marlon 👋, tu Action está funcionando correctamente!"
